Add script to lookup userids in identitystore.
symopsio/community-scripts pull request #1
Opened 2021-01-09 21:17 UTC by abuggia

2021-01-09 21:29 UTC, druiz approved these changes
That's cool! Might want to mention that they would need to be in an `aws-vault` session and maybe add some AWS account id informations to the output, so the user is clear on which account his identities are coming from.

2021-01-10 11:49 UTC, jon918 requested changes

2021-01-10 11:49 UTC, jon918 commented on sym_community_scripts/identitystore_userids.py
> +        response = self._list_users(UserName=username)
Looks like there is a filter option to find a specific user: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/identitystore.html#IdentityStore.Client.list_users

If that doesn't work, then i think this needs to account for pagination.

2021-01-10 11:50 UTC, jon918 commented on sym_community_scripts/identitystore_userids.py
> +        response = self._list_users(UserName=username)
I think that right now it is possible to only have one identity store per aws acct, so if not specified could look up the default identity store id.

2021-03-16 18:03 UTC, yasyf commented on sym_community_scripts/identitystore_userids.py
> +class IdentityStore:
Should inherit from the shared base class and use the helpers, if possible

2021-03-25 16:25 UTC, merged